export const SET_SECTION_DATA = "SET_SECTION_DATA";
export const ADD_SUB_ITEM_TO_CHANGES = "ADD_SUB_ITEM_TO_CHANGES";
export const REMOVE_ITEM_FROM_CHANGES = "REMOVE_ITEM_FROM_CHANGES";
export const REMOVE_SUB_ITEM_FROM_CHANGES = "REMOVE_SUB_ITEM_FROM_CHANGES";
