export const SET_SECTION_DATA = "SET_SECTION_DATA";
export const SAVE_MUUTOSPYYNTO_START = "SAVE_MUUTOSPYYNTO_START";
export const SAVE_MUUTOSPYYNTO_SUCCESS = "SAVE_MUUTOSPYYNTO_SUCCESS";
export const SAVE_MUUTOSPYYNTO_FAILURE = "SAVE_MUUTOSPYYNTO_FAILURE";
