export const FETCH_OPPILAITOKSENOPETUSKIELET_START =
  "FETCH_OPPILAITOKSENOPETUSKIELET_START";
export const FETCH_OPPILAITOKSENOPETUSKIELET_SUCCESS =
  "FETCH_OPPILAITOKSENOPETUSKIELET_SUCCESS";
export const FETCH_OPPILAITOKSENOPETUSKIELET_FAILURE =
  "FETCH_OPPILAITOKSENOPETUSKIELET_FAILURE";
