export const GET_VANKILAT = "GET_VANKILAT";
export const FETCH_VANKILAT_START = "FETCH_VANKILAT_START";
export const FETCH_VANKILAT_SUCCESS = "FETCH_VANKILAT_SUCCESS";
export const FETCH_VANKILAT_FAILURE = "FETCH_VANKILAT_FAILURE";
export const ADD_VANKILA = "ADD_VANKILA";
export const REMOVE_VANKILA = "REMOVE_VANKILA";
