export const FETCH_ELYKESKUKSET_START = 'FETCH_ELYKESKUKSET_START'
export const FETCH_ELYKESKUKSET_SUCCESS = 'FETCH_ELYKESKUKSET_SUCCESS'
export const FETCH_ELYKESKUKSET_FAILURE = 'FETCH_ELYKESKUKSET_FAILURE'