export const FETCH_KIELET_START = "FETCH_KIELET_START";
export const FETCH_KIELET_SUCCESS = "FETCH_KIELET_SUCCESS";
export const FETCH_KIELET_FAILURE = "FETCH_KIELET_FAILURE";
export const FETCH_OPPILAITOKSENOPETUSKIELET_START =
  "FETCH_OPPILAITOKSENOPETUSKIELET_START";
export const FETCH_OPPILAITOKSENOPETUSKIELET_SUCCESS =
  "FETCH_OPPILAITOKSENOPETUSKIELET_SUCCESS";
export const FETCH_OPPILAITOKSENOPETUSKIELET_FAILURE =
  "FETCH_OPPILAITOKSENOPETUSKIELET_FAILURE";
