export const FETCH_MUUTOSPYYNNOT_START = 'FETCH_MUUTOSPYYNNOT_START'
export const FETCH_MUUTOSPYYNNOT_SUCCESS = 'FETCH_MUUTOSPYYNNOT_SUCCESS'
export const FETCH_MUUTOSPYYNNOT_FAILURE = 'FETCH_MUUTOSPYYNNOT_FAILURE'