export const FETCH_MUUTOSPYYNTO_START = "FETCH_MUUTOSPYYNTO_START";
export const FETCH_MUUTOSPYYNTO_SUCCESS = "FETCH_MUUTOSPYYNTO_SUCCESS";
export const FETCH_MUUTOSPYYNTO_FAILURE = "FETCH_MUUTOSPYYNTO_FAILURE";
export const FETCH_MUUTOSPYYNNOT_START = "FETCH_MUUTOSPYYNNOT_START";
export const FETCH_MUUTOSPYYNNOT_SUCCESS = "FETCH_MUUTOSPYYNNOT_SUCCESS";
export const FETCH_MUUTOSPYYNNOT_FAILURE = "FETCH_MUUTOSPYYNNOT_FAILURE";
