export const GET_MUUTOSPERUSTELU_BY_KOODIARVO =
  "GET_MUUTOSPERUSTELU_BY_KOODIARVO";
export const FETCH_MUUTOSPERUSTELUT_START = "FETCH_MUUTOSPERUSTELUT_START";
export const FETCH_MUUTOSPERUSTELUT_SUCCESS = "FETCH_MUUTOSPERUSTELUT_SUCCESS";
export const FETCH_MUUTOSPERUSTELUT_FAILURE = "FETCH_MUUTOSPERUSTELUT_FAILURE";
