export const FETCH_KOULUTUSALAT_START = "FETCH_KOULUTUSALAT_START";
export const FETCH_KOULUTUSALAT_SUCCESS = "FETCH_KOULUTUSALAT_SUCCESS";
export const FETCH_KOULUTUSALAT_FAILURE = "FETCH_KOULUTUSALAT_FAILURE";
