export const FETCH_OPISKELIJAVUODET_START = "FETCH_OPISKELIJAVUODET_START";
export const FETCH_OPISKELIJAVUODET_SUCCESS = "FETCH_OPISKELIJAVUODET_SUCCESS";
export const FETCH_OPISKELIJAVUODET_FAILURE = "FETCH_OPISKELIJAVUODET_FAILURE";
