export const PAATOS_TILAT = {
  AVOIN: 'AVOIN',
  HYVAKSYTTY: 'HYVAKSYTTY',
  HYLATTY: 'HYLATTY',
  TAYDENNETTAVA: 'TAYDENNETTAVA',
  HYV_MUUTETTUNA: 'HYV_MUUTETTUNA',
  PASSIVOITU: 'PASSIVOITU'
}

export const VALMISTELU_FIELDS = {
  PAATOS: 'paatos'
}