export const FETCH_MAARAYSTYYPIT_START = "FETCH_MAARAYSTYYPIT_START";
export const FETCH_MAARAYSTYYPIT_SUCCESS = "FETCH_MAARAYSTYYPIT_SUCCESS";
export const FETCH_MAARAYSTYYPIT_FAILURE = "FETCH_MAARAYSTYYPIT_FAILURE";
