export const FETCH_KOULUTUSTYYPIT_START = 'FETCH_KOULUTUSTYYPIT_START'
export const FETCH_KOULUTUSTYYPIT_SUCCESS = 'FETCH_KOULUTUSTYYPIT_SUCCESS'
export const FETCH_KOULUTUSTYYPIT_FAILURE = 'FETCH_KOULUTUSTYYPIT_FAILURE'