export const LOGIN_GET_ROLES_START = "LOGIN_GET_ROLES_START";
export const LOGIN_GET_ROLES_SUCCESS = "LOGIN_GET_ROLES_SUCCESS";
export const LOGIN_GET_ROLES_FAILURE = "LOGIN_GET_ROLES_FAILURE";

export const LOGOUT_USER_START = "LOGOUT_USER_START";

export const GET_ORGANISATION_START = "GET_ORGANISATION_START";
export const GET_ORGANISATION_SUCCESS = "GET_ORGANISATION_SUCCESS";
export const GET_ORGANISATION_FAILURE = "GET_ORGANISATION_FAILURE";